### PR TITLE
SCP-106 (Ready)

### PR DESCRIPTION
**Pull request by kachnov**

### CODE REVIEW

**Comment by JakeDaBoss** [comment]
Thanks for fixing the compiling issue.

**Comment by JakeDaBoss** [comment]
Much obliged. What's left for now?

**Comment by JakeDaBoss** [comment]
Oh, right, the map markers.

**Comment by JakeDaBoss** [comment]
@kachnov this does not compile currently, it appears.

**Comment by JakeDaBoss** [comment]
Oh, and another thing. Please add in that after 106 receives x amount of brute damage, he is forced to retreat to the pocket dimension, and heals there, and then has the ability to move back to the facility.

**Comment by kachnov** [comment]
Almost everything is done. Going to do some more testing tomorrow, but the SCP should work.

**Comment by kachnov** [comment]
For some reason Travis failed, but I just confirmed that the code compiles. You might want to look into that @JakeDaBoss

**Comment by JakeDaBoss** [comment]
You sure? Looks like it failed after that icon addition.

**Comment by kachnov** [comment]
It compiles anyway, something else has to be causing it. I don't know how Travis works so maybe?

**Comment by JakeDaBoss** [comment]
I'll wait for some more updates, to see if it fixes itself.

**Comment by kachnov** [comment]
closing this PR, new one to experimental has been opened

**Pull request closed without merging**
