### PR TITLE
De-retardshirams Site13

### PR DESCRIPTION
**Pull request by LYNXEMS**
The issues Told me were fixed including

>Class D Medbay
>Change of Medbay Colors
>Deleting Too large Secure Storage, oofie
>Making a few places in LCZ smaller and better placed
>A few misc fixes
>Removing bodies
>Removed SCP 055

### CODE REVIEW

**Comment by LYNXEMS** [comment]
lcz
LCZ changed to be more confusing and less space wasting with the removal of secure storage, blank space will be filled in as we add more SCPs

dmed
Class D Medical Zone

medbay
Medbay made racist , tiles changed to white, chemistry stocked with phoron and needed tools

Other than that, meny decals were removed, checkpoints now require only one person to man, and have something to do!

**Comment by JakeDaBoss** [comment]
Build faling.

**Comment by LYNXEMS** [comment]
code/modules/reagents/Chemistry-Recipes.dm:1965:error: 10: invalid expression (909)

Here lies the problem, Affie's PR is conflicting

**Comment by Affurit** [comment]
Close it and open it again @LYNXEMS

**Comment by LYNXEMS** [comment]
The PR is now compiling, awaiting merge, so I can start the large PR I will need some help with.

Also, if any more issues are found, I will fix them immediately similar to this PR

**Pull request merged**
