### PR TITLE
alright no

### PR DESCRIPTION
**Pull request by ghost**
capture

staph it you're embarrassing the other SCP-13 devs

### CODE REVIEW

**Review by kachnov — APPROVED** [review]
code is fine

**Review by rhicora — CHANGES_REQUESTED** [review]
The statues are fine, decor in the lobby is good. 

I'd approve if you wanted to change the description to something less ... lionizing.

**Comment by Pantherfist** [comment]
uhh the statues without description are still narcistic and the sprites suck

**Comment by Injazz** [comment]
this meme was made by tiger gang

**Comment by rhicora** [comment]
You guys are going to lose your shit when you find out about Lion Bars.

**Comment by Injazz** [comment]
okay this is epic

**Comment by Pantherfist** [comment]
Lion bars jesus christ this guy needs a doctor

**Comment by Kmc2000** [comment]
ok this is epic

**Comment by HeyBanditoz** [comment]
Include me in the screenshot thanks.

**Comment by rhicora** [comment]
Plot twist and new plan for revising this feature.

image

**Comment by ghost** [comment]
OOF

**Comment by Ziiro** [comment]
Alright so SCP-13 is a project by Lion for Lion and the rest of you are just peasants serving him. I hope this made you all learn your place!

**Comment by Pandolphina** [comment]
Alexa this is so sad play Thunderdome.ogg

**Pull request closed without merging**
