### PR TITLE
-snip-

### PR DESCRIPTION
**Pull request by FatCat1978**
Just someone being rude.

### CODE REVIEW

**Review by kachnov — APPROVED** [review]

**Comment by Affurit** [comment]
S A L T

We have priorities, and we honestly expected people to have common sense and not make IPC characters while the race was disabled.

**Comment by FatCat1978** [comment]
You've got really shitty priorities if your priorities can't include spending a solid 4 seconds fixing something; instead of tying up administration for longer than the issue took to fix.

Calling someone an idiot also != salt. this entire thing was a mockery of Lion's ignorance. 

If your design philosophy includes being a lazy as hell collective heap of shitcode and just going "lol it's against the rules!11", then your  priorities are rightly fucked, and the server will inevitably wind up aborted.

**Comment by JakeDaBoss** [comment]
Leave this issue be. It got fixed and that's what matters. This is not the place to air dirty laundry.

**Comment by Affurit** [comment]
Salty af then, lmao.

We'll see how our server turns out in time.

This is TESTING, not a final product that is refined, we made this very fucking clear, so think about using a different word to ignorance next time.

That is all.

**Comment by ghost** [comment]
says the guy who has a fork of vorestation

**Comment by JakeDaBoss** [comment]
> says the guy who has a fork of vorestation

Unless you want a repo ban too, I suggest to cool it and leave dead issues alone.

**Comment by ghost** [comment]
damage control at its finest

i don't give a shit if you repoban me either it's not like I want to contribute to shitcode and make your pockets fill with more patreon money

**Comment by JakeDaBoss** [comment]
> damage control at its finest
> 
> i don't give a shit if you repoban me either it's not like I want to contribute to shitcode and make your pockets fill with more patreon money

Damage control or just removing someone's toxic title. They didn't make a CL, I'd have compiled it.

I wish you all the best, pal. Join your toxic friend.

**Comment by Affurit** [comment]
This little clique is the most pathetic thing I’ve seen, honestly. 

What does that even mean? 

Y’all so sad.

**Pull request merged**
