### PR TITLE
Adds mapmerger2 + cleanups obsolete/pointless files

### PR DESCRIPTION
**Pull request by praisenarsie**
This adds the most up-to-date mapmerger tool (credits to SpaceManiac from /tg/).
Removes the obsolete mapmerger tools plus removed the pointless .int & .rsc files.
Renames maps to _maps so I don't have to edit mapmerger2.
Finally, mapmerges most of every map.

Keep in mind, if you are making edits to any map from now on. You must use mapmerger2 as it makes it easier for maintainers to view changes done to a map.

@SS13-SCP13/developers @SS13-SCP13/head-of-teams

### CODE REVIEW

**Comment by praisenarsie** [comment]
@JakeDaBoss Adds travis already. :(

**Comment by MrFroztee** [comment]
When you say adds most of "every map", how many maps are we talking

**Comment by praisenarsie** [comment]
every map apart from 2 which didn't work for some reason

**Comment by praisenarsie** [comment]
redoing this because >git

**Pull request closed without merging**
