### PR TITLE
SCP-049, SCP-106 fixes and tweaks

### PR DESCRIPTION
**Pull request by kachnov**

### CODE REVIEW

**Comment by JakeDaBoss** [comment]
How is the infection handled? Who's given it, and by what identifiers are they given this?

**Comment by JakeDaBoss** [comment]
As an added note, anyone who attacks SCP-049 through any means, should be given the pestilence overlay making them fair game, else that will become a one-sided battle 049 will lose.

**Comment by kachnov** [comment]
@JakeDaBoss Added. By default, there's a small chance for everyone to acquire the Pestilence, every life tick. 1 in 2,000 every 2 seconds.

**Comment by kachnov** [comment]
Actually I still need to account for people who shoot SCP-049 with guns

**Comment by JakeDaBoss** [comment]
Add a check for if a person has been affected by SCP-049, and removes the pestilence once turned. From there on, if they are revived by SCP-500, have it re-add the pestilence.

Also make sure SCP-106 cannot be targeted with this, and did you disable SCP-049 and 106 interaction, from both sides?

**Comment by kachnov** [comment]
Not yet.

**Comment by JakeDaBoss** [comment]
Possibly good to do that right away. Technically speaking we just need to block all sentient SCP's from affecting eachother. They usually have a common goal. Could nip a lot of potential grief in the bud. >inb4 scp-049-1-106 who doesn't claw you, he teleports you but now answers to SCP-049. Preferably not.

ALSO! Add a separate talking channel for SCP-049 and SCP-049-1 instances.

**Comment by JakeDaBoss** [comment]
Also, I'm currently deliberating internally on making cross-SCP interaction, sentient or not, blocked.

**Review by JakeDaBoss — APPROVED** [review]
Appears fine and with all changes requested.

**Pull request merged**
