### PR TITLE
Site13 Nearing 1.0. Decal and sekrits update!

### PR DESCRIPTION
**Pull request by LYNXEMS**

### CODE REVIEW

**Comment by LYNXEMS** [comment]
Travis is failing because of Site53, my commits compile well

loading baystation12.dme
loading interface\skin.dmf
loading site13-1.dmm
loading site13-2.dmm
loading site13-3.dmm
loading site13-4.dmm
loading site13-5.dmm
loading site13-6.dmm
saving baystation12.dmb (DEBUG mode)
baystation12.dmb - 0 errors, 0 warnings (7/29/18 2:13 am)

**Comment by JakeDaBoss** [comment]
Any idea why Travis might be failing?

**Comment by LYNXEMS** [comment]
The command "source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup" exited with 0.
$ bash dm.sh -M${DM_MAPFILE} baystation12.dme
DM compiler version 512.1435
loading baystation12.mdme
loading interface/skin.dmf
loading site53-1.dmm
loading site53-2.dmm
loading site53-3.dmm
loading site53-4.dmm
loading site53-8.dmm
maps/site53/site53-8.dmm:789:error: cannot find file
maps/site53/site53-8.dmm:789:error: expected )
Failed to load map file /home/travis/build/SS13-SCP13/SS13-SCP13/maps/site53/site53-8.dmm.
baystation12.mdme.dmb - 2 errors, 0 warnings (7/29/18 12:12 am)

**Comment by LYNXEMS** [comment]
Should I switch the repo to compile Site13 Instead?

**Comment by JakeDaBoss** [comment]
No. And check the line it tells you, then find the error and fix it.

**Comment by LYNXEMS** [comment]
As I said, Site53 is not compiling, because Dream Maker cannot open site53-8.dmm and the Travis is set to compile Site53. My map files are working and compilable if you decide to compile with Site13. You asked me not to touch Site53 again before...

**Comment by JakeDaBoss** [comment]
I'm seeing two errors. That's not compiling to me.

**Comment by LYNXEMS** [comment]
Both are mentioning Site53, because the Travis check does not even check Site13, because the codebase on github is set to compile with Site53 in mind

**Comment by LYNXEMS** [comment]
If I set the github to load site13 instead of site53 it will compile happily

**Comment by JakeDaBoss** [comment]
Open up the file in notepad and look at the relevant line.

**Comment by LYNXEMS** [comment]
There was an inaccessible DMI referenced in site53-8.dmm, it was fixed, I used the one from experimental branch

**Pull request merged**
