### PR TITLE
[READY] Murder by train

### PR DESCRIPTION
**Pull request by Bxil**
It is finished, feel free to merge.

Ports Paradise's super modern tram system.

PS: Yes, this was mapmerged. I just had to move both CZs up with a few tiles on three maps.

### CODE REVIEW

**Comment by JakeDaBoss** [comment]
Travis didn't pass on your first commit.

**Comment by Bxil** [comment]
It got cancelled because I pushed the second one.

**Comment by JakeDaBoss** [comment]
Oh right, I keep forgetting that.

**Review by kachnov — APPROVED** [review]

**Comment by JakeDaBoss** [comment]
Please open this on the new repo once it's up.

**Pull request closed without merging**
