### PR TITLE
Makes randown events a bit more lore friendly.

### PR DESCRIPTION
**Pull request by M11gamer**

### CODE REVIEW

**Review by rhicora — COMMENTED** [review]
Change "recuperated his structural integrity" to "recuperated its...", unless the cave system is male ; )

**Comment by rhicora** [comment]
I can re-enable meteor in my pull if it works properly as a cave-in. https://github.com/SS13-SCP13/SS13-SCP13/pull/502

**Comment by M11gamer** [comment]
Done

**Comment by M11gamer** [comment]
I think is broken right now because we don't have any space tiles to spawn the meteors in.

**Comment by rhicora** [comment]
I will leave it turned off in my pull then, for now.

**Review by rhicora — APPROVED** [review]

**Pull request merged**
