### PR TITLE
Small Engineering Fixes

### PR DESCRIPTION
**Pull request by M11gamer**
Fixed CE blast doors, CE atmos, fixed the missing pipe in engineering, fixed missing atmos controller in nuke room.

### CODE REVIEW

**Comment by JakeDaBoss** [comment]
APC wasn't missing in nuke vault... It was beside the blastdoor since it doesn't work otherwise.

**Comment by M11gamer** [comment]
oh sorry, but the atmos controller is missing right?

**Comment by JakeDaBoss** [comment]
Not sure about that one.

**Comment by JakeDaBoss** [comment]
APC didn't work when it was going underneath the cyllinder holders.

**Comment by M11gamer** [comment]
Removed

**Comment by JakeDaBoss** [comment]
Nois.

**Comment by JakeDaBoss** [comment]
Will merge after alpha.

**Pull request merged**
