### PR TITLE
Dark Spooky UI

### PR DESCRIPTION
**Pull request by LYNXEMS**
Before
light
After
darkmode

PRing requested by our staff

### CODE REVIEW

**Comment by JakeDaBoss** [comment]
Did you alter previous UI skins?

**Comment by LYNXEMS** [comment]
I only changed the colours of the outside user interface - Interface.dmf - what is seen on the pic. I could have messed with the chat window, but it would require some color tweaking for everything

**Comment by JakeDaBoss** [comment]
I'm inquiring towards pre-existing stuff. You added a new UI method, right?

**Comment by LYNXEMS** [comment]
No, I only edited colors of pre existing parts, look at the change in code, apparently also made a few parts have lowercase names instead, not breaking anything, because Dream Maker saved it that way

**Comment by JakeDaBoss** [comment]
If this is editing pre-existing UI, then I won't merge it.

**Pull request closed without merging**
