### PR TITLE
SCP-106 PD Update

### PR DESCRIPTION
**Pull request by ParnnVuhe**
**Pocket Dimension**
- Adds a Throne Room, Coffin Room, and other additional rooms to further inspire the hunt.
- Makes it so unpowered doors automatically close.

Gyazo: https://gyazo.com/2730c10d08c028afb466032d6b3b21ee

### CODE REVIEW

**Review by kachnov — APPROVED** [review]

**Comment by JakeDaBoss** [comment]
Please present the changes to me in a DM, and the affected map file to make integration into the update smoother.

**Comment by JakeDaBoss** [comment]
Due to the PD being as fucked up as it is with the damage variables, I'm stashing this indefinitely until such time that it is fixed.

**Review by JakeDaBoss — CHANGES_REQUESTED** [review]
Do not merge until said otherwise.

**Comment by JakeDaBoss** [comment]
Committed in 2b69b90157ce7fbf626769cf3d4a8fce4a4a2a58

**Pull request closed without merging**
