### PR TITLE
DMAPI Try 2

### PR DESCRIPTION
**Pull request by ghost**
***rust_g.dll needs to be moved out of the tools folder, next to the dme/dmb!***

### CODE REVIEW

**Comment by ghost** [comment]
Works.

**Comment by ghost** [comment]
Issues that lion pointed out are not present (such as lack of title screen or admins not loading)

**Comment by JakeDaBoss** [comment]
Remains DNR until I have the time to fully check out TGS4.

**Comment by ghost** [comment]
I've used it on a different server, it's pretty nice

**Review by kachnov — APPROVED** [review]

**Pull request merged**
