### PR TITLE
D-Class Orientation Paper

### PR DESCRIPTION
**Pull request by JarlElbow**

### CODE REVIEW

**Comment by JakeDaBoss** [comment]
Formatting looks good. For my own keepsake I'm keeping this open until tomorrow so I don't forget about it from a map perspective.

**Comment by rhicora** [comment]
It's in everyone's pocket to begin with so I don't think it will need to be on the map.

**Review by rhicora — APPROVED** [review]

**Comment by JakeDaBoss** [comment]
That does make my life easier. But papers still needa be removed from cells.

**Comment by rhicora** [comment]
I think it is fine to give them some papers to color on with crayons if that's what they're into.

**Pull request merged**
