### PR TITLE
Lion has Big BRAIN

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
Sure Bud

I did this in 3 minutes, with a newfound tool known as, "Find and Replace"

Big Think

### CODE REVIEW

**Comment by rhicora** [comment]
image

**Comment by CthulhuOnIce** [comment]
Alright, give me a moment.

**Comment by UndeadNappist** [comment]
This changes hierarchy pathing and will break everything, particularly to icon-states or map objects already in the game.

**Comment by rhicora** [comment]
I would really recommend just doing this find/replace to strings to start with, to avoid touching hierarchy.

**Comment by JakeDaBoss** [comment]
Doubt this is going to pass.

**Comment by CthulhuOnIce** [comment]
call it a WIP
still hardly a pain

**Comment by JakeDaBoss** [comment]
Gonna call it open and shut poor tactics.

**Comment by CthulhuOnIce** [comment]
Big think

**Comment by rhicora** [comment]
I would like to review a strings-only version of this pull if you're up for it.

**Comment by CthulhuOnIce** [comment]
@JakeDaBoss I fixed it papa

**Comment by rhicora** [comment]
We can all try to be less snarky to each other.

**Comment by CthulhuOnIce** [comment]
I would recommend re-opening this PR. I fixed the like, 4 compile errors.

**Comment by rhicora** [comment]
image

Still some references to "NT " in strings, as well as station, space, etc.

**Comment by CthulhuOnIce** [comment]
That can be done seperately, but the bulk of the problem is solved, but i'll commit a "NT* fix anyway

**Comment by UndeadNappist** [comment]
Icons are binary files. The find and replace tool in Atom or similar does not read those. This will produce completely invisible objects and items, or spawn error sprites, because there is no associated icon.

The map will also need to be updated.

Furthermore, even if reverted back to use those icons, many of them have NT symbols or are not thematically appropriate (visually) to the SCP setting.

**Comment by CthulhuOnIce** [comment]
Like, i can put actual effort into changing all this stuff, but the main idea was to prove a point.

**Comment by UndeadNappist** [comment]
This was literally the first thing I tried myself. Please stop sniping at each other.

**Comment by rhicora** [comment]
I think the point that has been proven here is that actual effort is required. It's more complex than a find and replace. We need to avoid touching hierarchy to prevent icons from breaking.

Todo: replace occurrences of "NanoTrasen" in strings only, and then handle edge cases with " NT", "NT ", references to space or a station.

**Comment by CthulhuOnIce** [comment]
Actual effort != An actual pain.

**Comment by rhicora** [comment]
I agree, but some pain might arise from trying to do this plus several other things that need actual effort by this Friday (comms rework, supply shuttle fix, transfer shuttle changes).

**Pull request closed without merging**
